### ISSUE TITLE
Broken Image Link / Badge in README.md

### ISSUE THREAD

**Issue by MagusWyvern** [pvcodes/pi_wallet#3]
There appears to be a broken link contained in the README.md of the repository, upon further inspection it reveals that the LICENSE.md file does not exist at https://github.com/pvcodes/pi_wallet/blob/main/docs/LICENSE.md. Perhaps the file got deleted or didn't exist in the first place?

https://shields.io/ also returned a 404 for the LICENSE badge. I suggest either creating the LICENSE.md file or commenting out the section of code that displays the badge for now.

In Web View of Repository:
![image](https://user-images.githubusercontent.com/72914828/233218124-567b355a-1235-4f1b-8513-e0b48983f4e4.png)

In VSCode Preview of README.md file:
![image](https://user-images.githubusercontent.com/72914828/233218197-e441db93-d2bf-4ca8-bbf4-71c941e71789.png)

**Comment by pvcodes** [comment]
Thanks for pointing out, also it has been fixed in recent [commit](https://github.com/pvcodes/pi_wallet/commit/c89485e47f4ef7a49875ef45778d5dcbbc263f01#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

**Comment by MagusWyvern** [comment]
Alright, closing this as completed then 👍🏻
